import React, { createContext, useContext, useState, useEffect } from 'react'; 
 
type Language = 'en' | 'bg'; 
 
interface LanguageContextType { 
  language: Language; 
  setLanguage: (lang: Language) => void; 
  t: (key: string) => string;  
} 
  
const LanguageContext = createContext<LanguageContextType | undefined>(undefined); 
 
// eslint-disable-next-line react-refresh/only-export-components   
export const useLanguage = () => { 
  const context = useContext(LanguageContext); 
  if (!context) { 
    throw new Error('useLanguage must be used within LanguageProvider');  
  } 
  return context; 
}; 
 
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => { 
  const [language, setLanguage] = useState<Language>(() => { 
    const saved = localStorage.getItem('language'); 
    return (saved as Language) || 'en'; 
  }); 
 
  useEffect(() => { 
    localStorage.setItem('language', language); 
  }, [language]); 

  const t = (key: string): string => {
    const translations = language === 'bg' ? bgTranslations : enTranslations;
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const enTranslations: Record<string, string> = {

  // Navigation
  'nav.home': 'Home',
  'nav.learn': 'Learn',
  'nav.compete': 'Compete',
  'nav.community': 'Community',
  'nav.profile': 'Profile',
  'nav.PIG': 'PIG',
  'nav.login': 'Login',
  'nav.signup': 'Sign Up',

  // Login Page
  'login.title': 'Welcome Back',
  'login.subtitle': 'Login to your PIG account',
  'login.email': 'Email',
  'login.emailPlaceholder': 'you@example.com',
  'login.password': 'Password',
  'login.passwordPlaceholder': 'Enter your password',
  'login.loginButton': 'Login',
  'login.noAccount': "Don't have an account?",
  'login.signupLink': 'Sign up',

  // Signup Page
  'signup.title': 'Create Account',
  'signup.subtitle': 'Join PIG today',
  'signup.name': 'Name',
  'signup.namePlaceholder': 'Your name',
  'signup.email': 'Email',
  'signup.emailPlaceholder': 'you@example.com',
  'signup.password': 'Password',
  'signup.passwordPlaceholder': 'Create a password',
  'signup.confirmPassword': 'Confirm Password',
  'signup.confirmPasswordPlaceholder': 'Confirm your password',
  'signup.signupButton': 'Sign Up',
  'signup.haveAccount': 'Already have an account?',
  'signup.loginLink': 'Login',

  // Home Page
  'home.hero.title': 'Lets Protect Our Planet,',
  'home.hero.title.highlight': 'Together',
  'home.hero.subtitle': 'Join students from around the world in learning about nature conservation and making a real difference in your community',
  'home.hero.start': 'Start Learning',
  'home.hero.view': 'View Competitions',
  'home.features.title': 'Everything You Need to Make a Difference',
  'home.features.subtitle': 'Our platform combines education, competition, and community to inspire environmental action',
  'home.feature1.title': 'Learn & Discover',
  'home.feature1.desc': 'Explore why nature conservation matters and how every action counts',
  'home.feature2.title': 'Compete & Win',
  'home.feature2.desc': 'Join weekly, monthly, and yearly competitions between cities and schools',
  'home.feature3.title': 'Share & Connect',
  'home.feature3.desc': 'Celebrate achievements and inspire others in your school community',
  'home.stats.trees': 'Trees Planted',
  'home.stats.schools': 'Schools Participating',
  'home.stats.students': 'Students Engaged',
  'home.see.more': 'Explore',

  // Profile Page
  'profile.title': 'My Profile',
  'profile.subtitle': 'Track your environmental impact and achievements',
  'profile.overview': 'Overview',
  'profile.settings': 'Settings',
  'profile.points': 'Total Points',
  'profile.trees': 'Trees Planted',
  'profile.challenges': 'Challenges Done',
  'profile.lessons': 'Lessons Finished',
  'profile.achievements': 'Recent Achievements',
  'profile.goals': 'Active Goals',
  'profile.newGoal': 'Set New Goal',
  'profile.createGoal': 'Create a New Goal',
  'profile.goalTitle': 'Goal Title',
  'profile.goalDesc': 'Description',
  'profile.goalPlaceholder': 'e.g., Plant 100 Trees',
  'profile.goalDescPlaceholder': 'Describe your goal...',
  'profile.createButton': 'Create Goal',
  'profile.settingsTitle': 'Profile Settings',
  'profile.name': 'Full Name',
  'profile.email': 'Email',
  'profile.school': 'School',
  'profile.role': 'Role',
  'profile.edit': 'Edit Profile',
  'profile.save': 'Save Changes',
  'profile.cancel': 'Cancel',
  'profile.updated': 'Profile updated!',
  'profile.updatedDesc': 'Your profile has been saved successfully.',
  'profile.goalCreated': 'Goal created!',
  'profile.goalCreatedDesc': 'Your new goal has been added successfully.',
  'profile.goalDeleted': 'Goal deleted',
  'profile.goalDeletedDesc': 'Your goal has been removed.',
  'profile.progressUpdated': 'Progress Updated',
  'profile.progressUpdatedDesc': 'Your goal progress has been updated.',
  'profile.language': 'Language',
  'profile.languageDesc': 'Switch website language',
  'profile.darkMode': 'Dark Theme',
  'profile.darkModeDesc': 'Toggle between light and dark theme',
  'profile.light': 'Light',
  'profile.dark': 'Dark',

  // Achievements
  'achievement.treePlanter': 'Tree Planter',
  'achievement.treePlanterDesc': 'Planted 10 trees',
  'achievement.quizMaster': 'Quiz Master',
  'achievement.quizMasterDesc': 'Completed 5 quizzes with 100%',
  'achievement.champion': 'Community Champion',
  'achievement.championDesc': 'Reached 1000 points',

  // Time
  'time.daysAgo': 'days ago',
  'time.weekAgo': 'week ago',
  'time.weeksAgo': 'weeks ago',

  // Common
  'common.student': 'Student',
  'common.goldTier': 'Gold Tier',

  // Footer
  'footer.tagline': 'Empowering students worldwide to protect our planet through education and action.',
  'footer.platform': 'Platform',
  'footer.resources': 'Resources',
  'footer.legal': 'Privacy Notice',
  'footer.aboutUs': 'About Us',
  'footer.contact': 'Contact',
  'footer.faq': 'FAQ',
  'footer.privacy': 'Privacy Policy',
  'footer.terms': 'Terms of Service',
  'footer.rights': 'All rights reserved.',
  'footer.madeWith': 'Made with 💚 for a greener planet',

  // About
  'about.title': 'Paint IT Green',
  'about.subtitle': 'Empowering the next generation to protect our planet through education, competition, and community action.',
  'about.mission': 'Our Mission',
  'about.missionText1': 'PIG is dedicated to creating a global community of environmentally conscious students who understand the importance of protecting our planet.',
  'about.missionText2': 'Through interactive learning, friendly competition, and community engagement, we inspire students of all ages to take meaningful action in preserving nature.',

  // Learn
  'learn.title': 'Learn About Nature Conservation',
  'learn.subtitle': 'Discover why protecting our environment is crucial and how you can make a difference',
  'learn.wildlife': 'Wildlife Protection',
  'learn.pollution': 'Fighting Pollution',
  'learn.recycling': 'Recycling & Reusing',
  'learn.forests': 'Forest Conservation',
  'learn.water': 'Water Conservation',
  'learn.communityAction': 'Community Action',
  'learn.remember': 'Remember',
  'learn.rememberText': 'Every small action counts. Whether it\'s picking up litter, planting a tree, or teaching someone else about conservation - you\'re making a difference. Together, we can protect our beautiful planet for generations to come!',

  // Compete
  'compete.title': 'Competitions & Leaderboards',
  'compete.subtitle': 'See how cities, schools, and students are competing to make the biggest environmental impact',
  'compete.challenges': 'Timeline of challenges',
  'compete.leaderboards': 'Leaderboards',
  'compete.viewEvents': 'View Local Events',
  'compete.eventCalendar': 'Event Calendar',
  'compete.createEvent': 'Create Event',
  'compete.editEvent': 'Edit Event',
  'compete.eventTitle': 'Event Title',
  'compete.eventTitlePlaceholder': 'e.g., Park Cleanup',
  'compete.eventTime': 'Time',
  'compete.eventLocation': 'Location',
  'compete.eventLocationPlaceholder': 'e.g., Central Park',
  'compete.clickMapHint': 'Tip: Click on the map to set coordinates',
  'compete.saveEvent': 'Save Event',
  'compete.cancel': 'Cancel',
  'compete.selectDate': 'Select a date',
  'compete.adminMode': 'Admin Mode',
  'compete.noEvents': 'No events scheduled for this day.',
  'compete.confirmDelete': 'Are you sure you want to delete this event?',
  'compete.deleteError': 'Failed to delete. You might not be the owner.',
  'compete.past': 'Past',
  'compete.active': 'Active',
  'compete.upcoming': 'Upcoming',
  'compete.current': 'Current',
  'compete.currentMonth': 'Current Month',
  'compete.winners': 'Winners',
  'compete.lastWinners': "Last Month's Winners",
  'compete.allTimeShort': 'All-Time',
  'compete.allTime': 'All-Time Wins',
  'compete.lastWinnersRanking': 'Top Schools in Last Challenge:',
  'compete.allTimeRankings': 'All-Time Win Rankings',
  'compete.points': 'points',
  'compete.wins': 'wins',
  'compete.cities': 'Cities',
  'compete.schools': 'Schools',
  'compete.students': 'Students',
  'compete.cityRankings': 'City Rankings - Monthly',
  'compete.schoolRankings': 'School Rankings - Monthly',
  'compete.studentRankings': 'Student Rankings - Monthly',


  // 'compete.fakeChallange1NAME': 'Community Cleanup',
  // 'compete.fakeChallange1DATE': '',
  // 'compete.fakeChallange1INFO': '',

  // 'compete.fakeChallange2NAME': 'Water Savers',
  // 'compete.fakeChallange2DATE': '',
  // 'compete.fakeChallange2INFO': '',

  // 'compete.fakeChallange3NAME': 'Month of Recycling',  
  // 'compete.fakeChallange3DATE': '',
  // 'compete.fakeChallange3INFO': '',

  // 'compete.fakeChallange4NAME': 'Plant a Tree Week',
  // 'compete.fakeChallange4DATE': '',
  // 'compete.fakeChallange4INFO': '',

  // 'compete.fakeChallange5NAME': '',
  // 'compete.fakeChallange5DATE': '',
  // 'compete.fakeChallange5INFO': '',

  // Contact
  'contact.title': 'Contact Us',
  'contact.subtitle': 'Have questions? We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
  'contact.sendMessage': 'Send us a message',
  'contact.getInTouch': 'Get in touch',
  'contact.getInTouchText': 'Whether you\'re a student, teacher, or school administrator, we\'re here to help you make a difference.',
  'contact.email': 'Email',
  'contact.phone': 'Phone',
  'contact.address': 'Address',
  'contact.yourName': 'Your Name',
  'contact.yourEmail': 'Your Email',
  'contact.subject': 'Subject',
  'contact.yourMessage': 'Your Message',
  'contact.send': 'Send Message',

  // FAQ
  'faq.title': 'Frequently Asked Questions',
  'faq.subtitle': 'Find answers to common questions about PIG and how to get the most out of our platform.',

  // Privacy
  'privacy.title': 'Privacy Policy',
  'privacy.lastUpdated': 'Last updated:',

  // Terms
  'terms.title': 'Terms of Service',
  'terms.lastUpdated': 'Last updated:',

  // 404
  'notFound.title': '404',
  'notFound.subtitle': 'Oops! Page not found',
  'notFound.home': 'Return to Home',

  // Our Goal
  'ourGoal.title': 'Our Goal',
  'ourGoal.subtitle': 'Making environmental education accessible to every student worldwide',
  'ourGoal.breaking': 'Breaking Down Barriers',
  'ourGoal.breakingText': 'We believe that every student, regardless of their location, economic status, or background, deserves access to quality environmental education. Our platform removes traditional barriers by providing free, engaging, and comprehensive learning resources.',
  'ourGoal.freeResources': 'Free Resources',
  'ourGoal.freeResourcesDesc': 'All our educational materials are completely free and available to students worldwide.',
  'ourGoal.globalReach': 'Global Reach',
  'ourGoal.globalReachDesc': 'Available in multiple languages, reaching students across continents and cultures.',
  'ourGoal.inclusiveLearning': 'Inclusive Learning',
  'ourGoal.inclusiveLearningDesc': 'Designed for diverse learning styles and abilities, ensuring everyone can participate.',
  'ourGoal.vision': 'Our Vision for the Future',
  'ourGoal.visionText': "By 2030, we aim to reach 10 million students across 150 countries, creating a generation of environmentally conscious global citizens. We're not just teaching about climate change—we're empowering students to become active participants in solving it.",
  'ourGoal.joinMission': 'Join Our Mission',
  'ourGoal.joinMissionText': "Whether you're a student, teacher, or school administrator, you can be part of this global movement to make environmental education accessible to all.",
  'ourGoal.startLearning': 'Start Learning Today',

  // Our Community
  'ourCommunity.title': 'Our Community',
  'ourCommunity.subtitle': 'Connecting schools and students across the globe in a shared mission to protect our planet',
  'ourCommunity.globalNetwork': 'A Global Network of Change-Makers',
  'ourCommunity.globalNetworkText': "PIG connects students from diverse backgrounds and cultures, creating a vibrant community united by their passion for environmental protection. Our platform fosters collaboration, friendship, and collective action across borders.",
  'ourCommunity.shareConnect': 'Share & Connect',
  'ourCommunity.shareConnectDesc': 'Exchange ideas, share success stories, and collaborate on projects with students from around the world.',
  'ourCommunity.celebrateTogether': 'Celebrate Together',
  'ourCommunity.celebrateTogetherDesc': 'Recognize achievements, celebrate milestones, and inspire each other to reach new heights.',
  'ourCommunity.supportNetwork': 'Support Network',
  'ourCommunity.supportNetworkDesc': 'Find mentors, ask questions, and receive guidance from experienced environmental advocates.',
  'ourCommunity.schoolPartnerships': 'School Partnerships',
  'ourCommunity.schoolPartnershipsDesc': 'Connect your entire school with others worldwide for collaborative environmental initiatives.',
  'ourCommunity.impact': 'Community Impact',
  'ourCommunity.impactDesc': "Our community has planted over 50,000 trees, organized 1,000+ local cleanup events, and reached 500,000 students across 85 countries. Together, we're proving that collective action creates real change.",
  'ourCommunity.countries': 'Countries',
  'ourCommunity.studentsCount': 'Students',
  'ourCommunity.treesPlanted': 'Trees Planted',
  'ourCommunity.events': 'Events',
  'ourCommunity.joinCommunity': 'Join Our Community',
  'ourCommunity.joinCommunityText': 'Become part of a global movement of students taking action for our planet. Connect, share, and make a difference together.',
  'ourCommunity.exploreCommunity': 'Explore Community',

  // Our Impact
  'ourImpact.title': 'Our Impact',
  'ourImpact.subtitle': 'Real environmental change through collective action',
  'ourImpact.measurable': 'Measurable Environmental Change',
  'ourImpact.measurableText': 'Every action taken by our community creates real, lasting impact. From reducing plastic waste to planting forests, we track and celebrate every positive change our students make.',
  'ourImpact.treesPlantedTitle': 'Trees Planted',
  'ourImpact.treesPlantedDesc': 'Our reforestation projects have planted over 52,000 trees, absorbing thousands of tons of CO2 annually.',
  'ourImpact.plasticRemoved': 'Plastic Items Removed',
  'ourImpact.plasticRemovedDesc': 'Beach and community cleanups have removed over 2 million plastic items from natural environments.',
  'ourImpact.behaviorChange': 'Behavior Change',
  'ourImpact.behaviorChangeDesc': '85% of students report lasting changes in their environmental habits after completing our programs.',
  'ourImpact.schoolGardens': 'School Gardens',
  'ourImpact.schoolGardensDesc': 'Student-led initiatives have established over 150 sustainable school gardens worldwide.',
  'ourImpact.beyondNumbers': 'Beyond Numbers',
  'ourImpact.beyondNumbersText': "Our impact extends beyond statistics. Students develop leadership skills, schools implement sustainable policies, and communities become more environmentally conscious. We're creating a ripple effect that touches families, neighborhoods, and entire regions.",
  'ourImpact.studentStories': 'Student Stories',
  'ourImpact.studentStory1': 'Through P.I.G, our school planted 500 trees and inspired our entire city to start a recycling program. We are not just learning—we are leading change.',
  'ourImpact.studentStory1Author': '— Maria, 16, Brazil',
  'ourImpact.studentStory2': 'I organized my first beach cleanup thanks to P.I.G. Now we do it monthly with 50+ volunteers!',
  'ourImpact.studentStory2Author': '— David, 14, Philippines',
  'ourImpact.bePartOfImpact': 'Be Part of the Impact',
  'ourImpact.bePartText': 'Join thousands of students creating real environmental change. Your actions matter.',
  'ourImpact.startMakingImpact': 'Start Making Impact',

  // Our Values
  'ourValues.title': 'Our Values',
  'ourValues.subtitle': 'Education, action, and compassion for all living things',
  'ourValues.whatWeStandFor': 'What We Stand For',
  'ourValues.whatWeStandForText': 'Our values guide every decision we make and shape the culture of our global community. They reflect our commitment to creating a better world for all living things.',
  'ourValues.education': 'Education',
  'ourValues.educationText': 'Knowledge is power. We believe in making environmental education accessible, engaging, and actionable. Every student deserves to understand the science behind climate change and the solutions within their reach.',
  'ourValues.educationPoint1': 'Evidence-based learning materials',
  'ourValues.educationPoint2': 'Accessible to all, regardless of background',
  'ourValues.educationPoint3': 'Practical knowledge that leads to action',
  'ourValues.action': 'Action',
  'ourValues.actionText': 'Learning must lead to doing. We empower students to take meaningful action in their communities, turning awareness into impact. Every small action contributes to larger change.',
  'ourValues.actionPoint1': 'Hands-on environmental projects',
  'ourValues.actionPoint2': 'Community-led initiatives',
  'ourValues.actionPoint3': 'Measurable, real-world impact',
  'ourValues.compassion': 'Compassion',
  'ourValues.compassionText': 'Environmental protection starts with caring—for our planet, for all species, and for each other. We foster a community built on empathy, respect, and kindness.',
  'ourValues.compassionPoint1': 'Respect for all living things',
  'ourValues.compassionPoint2': 'Inclusive and supportive community',
  'ourValues.compassionPoint3': 'Understanding diverse perspectives',
  'ourValues.collaboration': 'Collaboration',
  'ourValues.collaborationText': 'No one can solve the climate crisis alone. We believe in the power of collective action, bringing together students, schools, and communities worldwide.',
  'ourValues.collaborationPoint1': 'Global network of change-makers',
  'ourValues.collaborationPoint2': 'Shared knowledge and resources',
  'ourValues.collaborationPoint3': 'Stronger together than apart',
  'ourValues.livingValues': 'Living Our Values',
  'ourValues.livingValuesText': "These aren't just words on a page—they're principles we practice every day. From how we design our curriculum to how we support our community, our values guide us forward.",
  'ourValues.livingValuesText2': 'When you join PIG, you become part of a movement that prioritizes education, celebrates action, practices compassion, and thrives on collaboration.',
  'ourValues.joinMission': 'Join Our Mission',
  'ourValues.joinMissionText': 'Ready to be part of a community that lives these values every day? Start your journey with PIG.',
  'ourValues.learnMore': 'Learn More About Us',

  // About Page Cards
  'about.ourGoal': 'Our Goal',
  'about.ourGoalDesc': 'Making environmental education accessible to every student worldwide',
  'about.ourCommunity': 'Our Community',
  'about.ourCommunityDesc': 'Connecting schools and students across the globe',
  'about.ourImpact': 'Our Impact',
  'about.ourImpactDesc': 'Real environmental change through collective action',
  'about.ourValues': 'Our Values',
  'about.ourValuesDesc': 'Education, action, and compassion for all living things',

  // Learn Page Topics and Content
  'learn.searchPlaceholder': 'Search topics...',
  'learn.topic.wildlife.title': 'Wildlife Protection',
  'learn.topic.wildlife.subtitle1': 'Why Every Animal Matters',
  'learn.topic.wildlife.text1': 'Every creature, from the smallest insect to the largest whale, plays a crucial role in our ecosystem. When one species disappears, it affects the entire food chain and can have devastating consequences for our planet.',
  'learn.topic.wildlife.subtitle2': 'How You Can Help',
  'learn.topic.wildlife.text2': 'Create wildlife-friendly spaces in your garden, avoid using harmful pesticides, support conservation organizations, and never litter in natural habitats. Small actions add up to big changes!',
  'learn.topic.pollution.title': 'Fighting Pollution',
  'learn.topic.pollution.subtitle1': 'The Impact of Pollution',
  'learn.topic.pollution.text1': 'Pollution harms our air, water, and soil. It affects not just wildlife, but our own health too. Plastic waste, chemical runoff, and air pollution are some of the biggest threats to our environment.',
  'learn.topic.pollution.subtitle2': 'Taking Action',
  'learn.topic.pollution.text2': 'Reduce single-use plastics, properly dispose of waste, use eco-friendly products, and encourage others to do the same. Every piece of trash properly disposed of is one less threat to our planet.',
  'learn.topic.recycling.title': 'Recycling & Reusing',
  'learn.topic.recycling.subtitle1': 'The Power of Recycling',
  'learn.topic.recycling.text1': 'Recycling saves natural resources, reduces landfill waste, and conserves energy. When we recycle paper, we save trees. When we recycle plastic, we reduce ocean pollution.',
  'learn.topic.recycling.subtitle2': 'How to Recycle Right',
  'learn.topic.recycling.text2': 'Learn what can be recycled in your area, clean items before recycling, reduce waste by reusing items, and compost organic waste. Make recycling a daily habit!',
  'learn.topic.forests.title': 'Forest Conservation',
  'learn.topic.forests.subtitle1': 'Why Forests Matter',
  'learn.topic.forests.text1': 'Forests are the lungs of our planet. They produce oxygen, store carbon dioxide, provide homes for countless species, and help regulate our climate. Protecting forests is crucial for our survival.',
  'learn.topic.forests.subtitle2': 'What You Can Do',
  'learn.topic.forests.text2': 'Plant trees, use less paper, choose sustainable wood products, and support reforestation efforts. Even planting one tree makes a difference!',
  'learn.topic.water.title': 'Water Conservation',
  'learn.topic.water.subtitle1': 'Water Is Precious',
  'learn.topic.water.text1': "Clean water is essential for all life on Earth. Yet, pollution and waste threaten our water sources. Only 3% of Earth's water is fresh water, and much of it is frozen in glaciers.",
  'learn.topic.water.subtitle2': 'Save Water Daily',
  'learn.topic.water.text2': 'Turn off taps when not in use, fix leaks, take shorter showers, and never pollute water sources. Every drop saved helps ensure water for future generations.',
  'learn.topic.community.title': 'Community Action',
  'learn.topic.community.subtitle1': 'Stronger Together',
  'learn.topic.community.text1': 'Individual actions are important, but when communities work together, we can achieve amazing things. Organize clean-up events, start recycling programs, and inspire others to join the cause.',
  'learn.topic.community.subtitle2': 'Getting Involved',
  'learn.topic.community.text2': 'Talk to your teachers about starting environmental projects, join or create eco-clubs, participate in community clean-ups, and share what you learn with friends and family.',
  'learn.topic.climate.title': 'Climate Change',
  'learn.topic.biodiversity.title': 'Biodiversity',
  'learn.topic.mountains.title': 'Mountain Ecosystems',
  'learn.topic.oceans.title': 'Ocean Life',
  'learn.topic.birds.title': 'Bird Conservation',
  'learn.topic.gardens.title': 'Sustainable Gardens',
  'learn.topic.global.title': 'Global Initiatives',
  'learn.topic.energy.title': 'Green Energy',
  'learn.topic.education.title': 'Eco Education',
  'learn.topic.agriculture.title': 'Sustainable Farming',
  'learn.topic.comingSoon': 'Coming Soon',
  'learn.topic.comingSoonText': 'Content will be added here.',
  'learn.watchVideo': 'Watch video on the topic',

  // FAQ Questions and Answers
  'faq.q1': 'What is P.I.G?',
  'faq.a1': 'P.I.G is an educational platform that teaches students about environmental conservation through interactive learning, competitions, and community engagement.',
  'faq.q2': 'Who can join P.I.G?',
  'faq.a2': 'P.I.G is open to students of all ages, teachers, school administrators, and parents. Each user type has different access levels and features.',
  'faq.q3': 'How do the competitions work?',
  'faq.a3': 'Competitions run weekly, monthly, and yearly at city, school, and individual student levels. Participants earn points for completing environmental challenges and actions.',
  'faq.q4': 'Is P.I.G free to use?',
  'faq.a4': 'Yes! P.I.G is completely free for all students and educators. Our mission is to make environmental education accessible to everyone.',
  'faq.q5': 'How can my school join?',
  'faq.a5': 'School administrators can register their school through our platform. Once registered, teachers can create groups and invite students to join.',
  'faq.q6': 'What kind of activities can we post?',
  'faq.a6': 'Schools can share photos and updates about recycling drives, tree planting events, clean-up activities, and any environmental initiatives undertaken by students.',
  'faq.q7': 'How are winners determined in competitions?',
  'faq.a7': 'Winners are determined by points earned through verified environmental actions. Schools and cities with the most active participants receive recognition.',
  'faq.q8': 'Can parents track their child progress?',
  'faq.a8': "Yes! Parents with accounts can follow their child's school group and see the environmental activities they're participating in.",

  // Privacy Page Content
  'privacy.intro': 'Introduction',
  'privacy.introText': 'At P.I.G, we take your privacy seriously. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our platform.',
  'privacy.collect': 'Information We Collect',
  'privacy.collectText': 'We collect information that you provide directly to us, including:',
  'privacy.collectItem1': 'Name, email address, and school information',
  'privacy.collectItem2': 'Account credentials',
  'privacy.collectItem3': 'Profile information and photos',
  'privacy.collectItem4': 'Posts, comments, and other content you share',
  'privacy.use': 'How We Use Your Information',
  'privacy.useText': 'We use the information we collect to:',
  'privacy.useItem1': 'Provide and maintain our services',
  'privacy.useItem2': 'Facilitate competitions and community features',
  'privacy.useItem3': 'Send you important updates and notifications',
  'privacy.useItem4': 'Improve our platform and user experience',
  'privacy.sharing': 'Information Sharing',
  'privacy.sharingText': 'We do not sell your personal information. We may share information with schools and parents as part of our educational mission, but only with appropriate consent.',
  'privacy.children': "Children's Privacy",
  'privacy.childrenText': "We are committed to protecting the privacy of children. Parents and guardians have control over their children's accounts and can review or delete information at any time.",
  'privacy.contact': 'Contact Us',
  'privacy.contactText': 'If you have questions about this Privacy Policy, please contact us.',

  // Terms Page Content
  'terms.acceptance': 'Acceptance of Terms',
  'terms.acceptanceText': 'By accessing and using P.I.G, you accept and agree to be bound by the terms and provisions of this agreement.',
  'terms.use': 'Use of Platform',
  'terms.useText': 'P.I.G is intended for educational purposes. Users agree to:',
  'terms.useItem1': 'Provide accurate information during registration',
  'terms.useItem2': 'Maintain the security of their account',
  'terms.useItem3': 'Use the platform responsibly and respectfully',
  'terms.useItem4': 'Not post harmful, offensive, or inappropriate content',
  'terms.accounts': 'School and Student Accounts',
  'terms.accountsText': 'School administrators are responsible for managing their school presence on the platform. Students under 13 must have parental consent to use the platform.',
  'terms.competition': 'Competition Rules',
  'terms.competitionText': 'Participants in competitions must follow all rules and guidelines. P.I.G reserves the right to disqualify participants who violate competition rules or engage in fraudulent activities.',
  'terms.content': 'Content Ownership',
  'terms.contentText': 'Users retain ownership of the content they post, but grant P.I.G a license to use, display, and distribute that content within the platform.',
  'terms.prohibited': 'Prohibited Activities',
  'terms.prohibitedText': 'Users may not:',
  'terms.prohibitedItem1': 'Violate any laws or regulations',
  'terms.prohibitedItem2': 'Harass or harm other users',
  'terms.prohibitedItem3': 'Attempt to access unauthorized areas of the platform',
  'terms.prohibitedItem4': 'Upload malicious code or spam',
  'terms.termination': 'Termination',
  'terms.terminationText': 'We reserve the right to terminate or suspend accounts that violate these terms or engage in inappropriate behavior.',
  'terms.changes': 'Changes to Terms',
  'terms.changesText': 'We may update these terms from time to time. Continued use of the platform after changes constitutes acceptance of the new terms.',
  'terms.contact': 'Contact',
  'terms.contactText': 'Questions about these Terms of Service can be directed to us.',

  // Profile
  'profile.complete': 'Complete',
  'profile.logout': 'Logout',

  // Community Page
  'community.title': 'Community',
  'community.public': 'Public Feed',
  'community.feeds': 'Feeds',
  'community.myGroups': 'My Groups',
  'community.moderation': 'Moderation',
  'community.globalCommunity': 'Global Community',
  'community.mySchool': 'My School',
  'community.myClass': 'My Class',
  'community.schoolGroup': 'School Group',
  'community.classGroup': 'Class Group',
  'community.publicSubtitle': 'Environmental initiatives from schools around the world',
  'community.schoolSubtitle': 'Updates and events from your school',
  'community.classSubtitle': 'Class discussions and projects',
  'community.groupUpdates': 'Group updates',
  'community.createPost': 'Create Post',
  'community.createNewPost': 'Create a new post',
  'community.sharePlaceholder': 'Share something with',
  'community.everyone': 'everyone',
  'community.yourGroup': 'your group',
  'community.photo': 'Photo',
  'community.post': 'Post',
  'community.noPostsYet': 'No posts yet',
  'community.beTheFirst': 'Be the first to share something with the',
  'community.communityWord': 'community!',
  'community.save': 'Save',
  'community.writeComment': 'Write a comment...',
  'community.commentAdded': 'Comment added!',
  'community.commentAddedDesc': 'Your comment has been posted successfully.',
  'community.postCreated': 'Post created!',
  'community.postCreatedDesc': 'Your post has been shared.',
  'community.postDeleted': 'Post deleted',
  'community.postDeletedDesc': 'Your post has been removed.',
  'community.postUpdated': 'Post updated',
  'community.postUpdatedDesc': 'Your post has been updated successfully.',
  'community.commentDeleted': 'Comment deleted',
  'community.commentDeletedDesc': 'Your comment has been removed.',
  'community.commentUpdated': 'Comment updated',
  'community.commentUpdatedDesc': 'Your comment has been updated successfully.',

  // Admin Panel
  'admin.title': 'Admin',
  'admin.managementConsole': 'Management Console',
  'admin.overview': 'Overview',
  'admin.groups': 'Groups',
  'admin.users': 'Users',
  'admin.reports': 'Reports',
  'admin.settings': 'Settings',
  'admin.exitMode': 'Exit Mode',
  'admin.adminConsole': 'Admin Console',
  'admin.createGroup': 'Create Group',
  'admin.systemOverview': 'System Overview',
  'admin.groupManagement': 'Group Management',
  'admin.userManagement': 'User Management',
  'admin.globalSettings': 'Global Settings',
  'admin.contentModeration': 'Content Moderation',
  'admin.manageSubtitle': 'Manage, monitor, and maintain community standards.',
  'admin.latestUpdates': 'Latest updates from your community.',
  'admin.totalUsers': 'Total Users',
  'admin.fromLastWeek': '+2% from last week',
  'admin.activeGroups': 'Active Groups',
  'admin.pendingReports': 'Pending Reports',
  'admin.actionRequired': 'Action required',
  'admin.allClear': 'All clear',
  'admin.systemStatus': 'System Status',
  'admin.serversOperational': 'Servers operational',
  'admin.globalAnnouncement': 'Global Announcement',
  'admin.announcementDesc': 'Send a system-wide broadcast to all active chat rooms.',
  'admin.announcementPlaceholder': "Type your message here (e.g., 'Server maintenance in 10 minutes')...",
  'admin.broadcast': 'Broadcast',
  'admin.announcementSent': 'Announcement Sent',
  'admin.announcementSentDesc': 'All users have been notified.',
  'admin.recentActivityLog': 'Recent Activity Log',
  'admin.activityLogDesc': 'Audit trail of administrative actions.',
  'admin.searchUsers': 'Search users by name or email...',
  'admin.exportCsv': 'Export CSV',
  'admin.user': 'User',
  'admin.role': 'Role',
  'admin.status': 'Status',
  'admin.actions': 'Actions',
  'admin.manage': 'Manage',
  'admin.viewProfile': 'View Profile',
  'admin.resetPassword': 'Reset Password',
  'admin.deleteAccount': 'Delete Account',
  'admin.chatGroups': 'Chat Groups',
  'admin.members': 'members',
  'admin.noDescription': 'No description',
  'admin.freeze': 'Freeze',
  'admin.unfreeze': 'Unfreeze',
  'admin.groupStatusUpdated': 'Group Status Updated',
  'admin.groupDeleted': 'Group Deleted',
  'admin.allCaughtUp': 'All Caught Up!',
  'admin.noPendingReports': 'No pending reports to review.',
  'admin.reported': 'Reported',
  'admin.reportedBy': 'Reported by',
  'admin.postContent': 'Post Content:',
  'admin.contentUnavailable': 'Content unavailable (Deleted or Error)',
  'admin.dismissReport': 'Dismiss Report',
  'admin.deletePost': 'Delete Post',
  'admin.contentRemoved': 'Content Removed',
  'admin.contentRemovedDesc': 'The post has been deleted permanently.',
  'admin.reportDismissed': 'Report Dismissed',
  'admin.safetyFilters': 'Safety & Filters',
  'admin.safetyFiltersDesc': 'Global settings for all chat rooms.',
  'admin.profanityFilter': 'Profanity Filter',
  'admin.profanityFilterDesc': 'Automatically hide offensive words.',
  'admin.imageUploads': 'Image Uploads',
  'admin.imageUploadsDesc': 'Allow users to send images in chats.',
  'admin.linkPreview': 'Link Preview',
  'admin.linkPreviewDesc': 'Generate previews for shared URLs.',
  'admin.dangerZone': 'Danger Zone',
  'admin.maintenanceMode': 'Enable Maintenance Mode',
  'admin.maintenanceModeDesc': 'This will lock all chat rooms for everyone except admins.',
  'admin.userBanned': 'User Banned',
  'admin.userUnbanned': 'User Unbanned',

  // Create Group Dialog
  'group.createTitle': 'Create New Group',
  'group.createDesc': 'Create a space for students and teachers to collaborate.',
  'group.orSelectPreset': 'Or select a preset:',
  'group.iconSelected': 'Icon Selected',
  'group.browseIcons': 'Browse Icons',
  'group.groupName': 'Group Name',
  'group.groupNamePlaceholder': 'e.g. Science Fair 2024',
  'group.description': 'Description',
  'group.descriptionPlaceholder': 'What is this group about?',
  'group.organization': 'Organization',
  'group.selectOrganization': 'Select organization',
  'group.none': 'None',
  'group.orgPassword': 'Organization Password',
  'group.orgPasswordNotRequired': 'Not required',
  'group.orgPasswordRequired': 'Required to link this organization',
  'group.privacyType': 'Privacy Type',
  'group.public': 'Public',
  'group.private': 'Private',
  'group.accessCode': 'Access Code',
  'group.accessCodePlaceholder': 'Set a password for joining...',
  'group.cancel': 'Cancel',
  'group.create': 'Create Group',
  'group.created': 'Group Created',
  'group.createdDesc': 'is now active.',

};

const bgTranslations: Record<string, string> = {

  // Navigation
  'nav.home': 'Начало',
  'nav.learn': 'Учене',
  'nav.compete': 'Състезания',
  'nav.community': 'Общност',
  'nav.profile': 'Профил',
  'nav.PIG': 'ЕкоУчене',
  'nav.login': 'Вход',
  'nav.signup': 'Регистрация',

  // Login Page
  'login.title': 'Добре дошли отново',
  'login.subtitle': 'Влезте в своя PIG акаунт',
  'login.email': 'Имейл',
  'login.emailPlaceholder': 'you@example.com',
  'login.password': 'Парола',
  'login.passwordPlaceholder': 'Въведете паролата си',
  'login.loginButton': 'Влез',
  'login.noAccount': 'Нямате акаунт?',
  'login.signupLink': 'Регистрирай се',

  // Signup Page
  'signup.title': 'Създай акаунт',
  'signup.subtitle': 'Присъедини се към PIG днес',
  'signup.name': 'Име',
  'signup.namePlaceholder': 'Вашето име',
  'signup.email': 'Имейл',
  'signup.emailPlaceholder': 'you@example.com',
  'signup.password': 'Парола',
  'signup.passwordPlaceholder': 'Създайте парола',
  'signup.confirmPassword': 'Потвърди парола',
  'signup.confirmPasswordPlaceholder': 'Потвърдете паролата си',
  'signup.signupButton': 'Регистрирай се',
  'signup.haveAccount': 'Вече имате акаунт?',
  'signup.loginLink': 'Влез',

  // Home Page
  'home.hero.title': 'Нека заедно защитим планетата ',
  'home.hero.title.highlight': 'НИ',
  'home.hero.subtitle': 'Присъединете се към ученици от цял свят в изучаването на опазването на природата и правенето на реална промяна във вашата общност',
  'home.hero.start': 'Започни да учиш',
  'home.hero.view': 'Виж състезанията',
  'home.features.title': 'Всичко необходимо за да направите промяна',
  'home.features.subtitle': 'Нашата платформа комбинира образование, състезания и общност, за да вдъхнови екологични действия',
  'home.feature1.title': 'Учи и откривай',
  'home.feature1.desc': 'Изследвайте защо опазването на природата е важно и как всяко действие има значение',
  'home.feature2.title': 'Състезавай се и печели',
  'home.feature2.desc': 'Присъединете се към седмични, месечни и годишни състезания между градове и училища',
  'home.feature3.title': 'Споделяй и свързвай',
  'home.feature3.desc': 'Празнувайте постижения и вдъхновявайте другите в училищната си общност',
  'home.stats.trees': 'Засадени дървета',
  'home.stats.schools': 'Участващи училища',
  'home.stats.students': 'Ангажирани ученици',
  'home.see.more': 'Вижте повече',

  // Profile Page
  'profile.title': 'Моят профил',
  'profile.subtitle': 'Проследете вашето екологично въздействие и постижения',
  'profile.overview': 'Преглед',
  'profile.settings': 'Настройки',
  'profile.points': 'Общо точки',
  'profile.trees': 'Засадени дървета',
  'profile.challenges': 'Завършени предизвикателства',
  'profile.lessons': 'Завършени уроци',
  'profile.achievements': 'Последни постижения',
  'profile.goals': 'Активни цели',
  'profile.newGoal': 'Задай нова цел',
  'profile.createGoal': 'Създай нова цел',
  'profile.goalTitle': 'Заглавие на целта',
  'profile.goalDesc': 'Описание',
  'profile.goalPlaceholder': 'напр., Засади 100 дървета',
  'profile.goalDescPlaceholder': 'Опишете вашата цел...',
  'profile.createButton': 'Създай цел',
  'profile.settingsTitle': 'Настройки на профила',
  'profile.name': 'Пълно име',
  'profile.email': 'Имейл',
  'profile.school': 'Училище',
  'profile.role': 'Роля',
  'profile.edit': 'Редактирай профила',
  'profile.save': 'Запази промените',
  'profile.cancel': 'Откажи',
  'profile.updated': 'Профилът е актуализиран!',
  'profile.updatedDesc': 'Вашият профил е запазен успешно.',
  'profile.goalCreated': 'Целта е създадена!',
  'profile.goalCreatedDesc': 'Вашата нова цел е добавена успешно.',
  'profile.goalDeleted': 'Целта е изтрита',
  'profile.goalDeletedDesc': 'Вашата цел е премахната.',
  'profile.progressUpdated': 'Прогресът е актуализиран',
  'profile.progressUpdatedDesc': 'Прогресът на вашата цел е актуализиран.',
  'profile.language': 'Език',
  'profile.languageDesc': 'Сменете езика на уебсайта',
  'profile.darkMode': 'Тъмна тема',
  'profile.darkModeDesc': 'Превключване между светла и тъмна тема',
  'profile.light': 'Светла',
  'profile.dark': 'Тъмна',

  // Achievements
  'achievement.treePlanter': 'Садител на дървета',
  'achievement.treePlanterDesc': 'Засади 10 дървета',
  'achievement.quizMaster': 'Майстор на теста',
  'achievement.quizMasterDesc': 'Завърши 5 теста със 100%',
  'achievement.champion': 'Шампион на общността',
  'achievement.championDesc': 'Достигна 1000 точки',

  // Time
  'time.daysAgo': 'дни преди',
  'time.weekAgo': 'седмица преди',
  'time.weeksAgo': 'седмици преди',

  // Common
  'common.student': 'Ученик',
  'common.goldTier': 'Златен ранг',

  // Footer
  'footer.tagline': 'Овластяваме учениците по целия свят да защитят нашата планета чрез образование и действие.',
  'footer.platform': 'Платформа',
  'footer.resources': 'Ресурси',
  'footer.legal': 'Поверителност',
  'footer.aboutUs': 'За нас',
  'footer.contact': 'Контакти',
  'footer.faq': 'Въпроси',
  'footer.privacy': 'Политика за поверителност',
  'footer.terms': 'Условия за ползване',
  'footer.rights': 'Всички права запазени.',
  'footer.madeWith': 'Направено с 💚 за по-зелена планета',

  // About
  'about.title': 'Нарисувай го в Зелено',
  'about.subtitle': 'Овластяваме следващото поколение да защитава нашата планета чрез образование, състезания и действия на общността.',
  'about.mission': 'Нашата мисия',
  'about.missionText1': 'PIG е посветен на създаването на глобална общност от екологично съзнателни ученици, които разбират важността на защитата на нашата планета.',
  'about.missionText2': 'Чрез интерактивно учене, приятелски състезания и ангажиране на общността, ние вдъхновяваме ученици от всички възрасти да предприемат значими действия за опазване на природата.',

  // Learn
  'learn.title': 'Научете за опазването на природата',
  'learn.subtitle': 'Открийте защо защитата на околната среда е от решаващо значение и как можете да направите промяна',
  'learn.wildlife': 'Защита на дивата природа',
  'learn.pollution': 'Борба със замърсяването',
  'learn.recycling': 'Рециклиране и повторна употреба',
  'learn.forests': 'Опазване на горите',
  'learn.water': 'Опазване на водата',
  'learn.communityAction': 'Действия на общността',
  'learn.remember': 'Запомнете',
  'learn.rememberText': 'Всяко малко действие има значение. Дали е вдигане на боклук, засаждане на дърво или обучаване на някой друг за опазване - вие правите промяна. Заедно можем да защитим нашата красива планета за бъдещите поколения!',
  'learn.watchVideo': 'Гледайте видео по темата',

  // Compete
  'compete.title': 'Състезания и класации',
  'compete.subtitle': 'Вижте как градове, училища и ученици се състезават за най-голямо екологично въздействие',
  'compete.challenges': 'Хронология на предизвикателства',
  'compete.leaderboards': 'Класации',
  'compete.viewEvents': 'Виж местните събития',
  'compete.eventCalendar': 'Календар със събития',
  'compete.createEvent': 'Създай събитие',
  'compete.editEvent': 'Редактирай събитие',
  'compete.eventTitle': 'Заглавие на събитието',
  'compete.eventTitlePlaceholder': 'напр., Почистване на парка',
  'compete.eventTime': 'Час',
  'compete.eventLocation': 'Място',
  'compete.eventLocationPlaceholder': 'напр., Централен парк',
  'compete.clickMapHint': 'Съвет: Кликнете върху картата за да зададете координати',
  'compete.saveEvent': 'Запази събитието',
  'compete.cancel': 'Откажи',
  'compete.selectDate': 'Изберете дата',
  'compete.adminMode': 'Администраторски режим',
  'compete.noEvents': 'Няма събития за този ден.',
  'compete.confirmDelete': 'Сигурни ли сте, че искате да изтриете това събитие?',
  'compete.deleteError': 'Неуспешно изтриване. Може да не сте собственик.',
  'compete.past': 'Минало',
  'compete.active': 'Активно',
  'compete.upcoming': 'Предстоящо',
  'compete.current': 'Текущ',
  'compete.currentMonth': 'Текущ месец',
  'compete.winners': 'Победители',
  'compete.lastWinners': 'Победители от миналия месец',
  'compete.allTimeShort': 'Всички времена',
  'compete.allTime': 'Победи за всички времена',
  'compete.lastWinnersRanking': 'Топ училища в последното предизвикателство:',
  'compete.allTimeRankings': 'Класация за всички времена',
  'compete.points': 'точки',
  'compete.wins': 'победи',
  'compete.cities': 'Градове',
  'compete.schools': 'Училища',
  'compete.students': 'Ученици',
  'compete.cityRankings': 'Класация на градовете - месечна',
  'compete.schoolRankings': 'Класация на училищата - месечна',
  'compete.studentRankings': 'Класация на учениците - месечна',

  // Contact
  'contact.title': 'Свържете се с нас',
  'contact.subtitle': 'Имате въпроси? Ще се радваме да чуем от вас. Изпратете ни съобщение и ще отговорим възможно най-скоро.',
  'contact.sendMessage': 'Изпратете ни съобщение',
  'contact.getInTouch': 'Свържете се',
  'contact.getInTouchText': 'Независимо дали сте ученик, учител или училищен администратор, ние сме тук, за да ви помогнем да направите промяна.',
  'contact.email': 'Имейл',
  'contact.phone': 'Телефон',
  'contact.address': 'Адрес',
  'contact.yourName': 'Вашето име',
  'contact.yourEmail': 'Вашият имейл',
  'contact.subject': 'Тема',
  'contact.yourMessage': 'Вашето съобщение',
  'contact.send': 'Изпрати съобщение',

  // FAQ
  'faq.title': 'Често задавани въпроси',
  'faq.subtitle': 'Намерете отговори на общи въпроси за PIG и как да получите най-доброто от нашата платформа.',

  // Privacy
  'privacy.title': 'Политика за поверителност',
  'privacy.lastUpdated': 'Последна актуализация:',

  // Terms
  'terms.title': 'Условия за ползване',
  'terms.lastUpdated': 'Последна актуализация:',

  // 404
  'notFound.title': '404',
  'notFound.subtitle': 'Опа! Страницата не е намерена',
  'notFound.home': 'Върнете се към начало',

  // Our Goal
  'ourGoal.title': 'Нашата цел',
  'ourGoal.subtitle': 'Правим екологичното образование достъпно за всеки ученик по света',
  'ourGoal.breaking': 'Преодоляване на бариерите',
  'ourGoal.breakingText': 'Вярваме, че всеки ученик, независимо от местоположението, икономическия статус или произхода си, заслужава достъп до качествено екологично образование. Нашата платформа премахва традиционните бариери, като предоставя безплатни, ангажиращи и изчерпателни учебни ресурси.',
  'ourGoal.freeResources': 'Безплатни ресурси',
  'ourGoal.freeResourcesDesc': 'Всички наши образователни материали са напълно безплатни и достъпни за ученици по целия свят.',
  'ourGoal.globalReach': 'Глобален обхват',
  'ourGoal.globalReachDesc': 'Достъпни на множество езици, достигащи до ученици в различни континенти и култури.',
  'ourGoal.inclusiveLearning': 'Приобщаващо учене',
  'ourGoal.inclusiveLearningDesc': 'Проектирани за различни стилове и способности за учене, осигуряващи възможност за участие на всички.',
  'ourGoal.vision': 'Нашата визия за бъдещето',
  'ourGoal.visionText': 'До 2030 г. се стремим да достигнем до 10 милиона ученици в 150 страни, създавайки поколение екологично съзнателни граждани на света. Не само преподаваме за климатичните промени - ние овластяваме учениците да станат активни участници в решаването им.',
  'ourGoal.joinMission': 'Присъединете се към нашата мисия',
  'ourGoal.joinMissionText': 'Независимо дали сте ученик, учител или училищен администратор, можете да бъдете част от това глобално движение за достъпно екологично образование за всички.',
  'ourGoal.startLearning': 'Започнете да учите днес',

  // Our Community  
  'ourCommunity.title': 'Нашата общност',
  'ourCommunity.subtitle': 'Свързваме училища и ученици по целия свят в обща мисия да защитим планетата',
  'ourCommunity.globalNetwork': 'Глобална мрежа от промяна',
  'ourCommunity.globalNetworkText': 'PIG свързва ученици от различни произходи и култури, създавайки жизнена общност, обединена от страстта си към опазването на околната среда. Нашата платформа насърчава сътрудничеството, приятелството и колективните действия отвъд границите.',
  'ourCommunity.shareConnect': 'Споделяй и се свързвай',
  'ourCommunity.shareConnectDesc': 'Обменяйте идеи, споделяйте истории за успех и си сътрудничете по проекти с ученици от цял свят.',
  'ourCommunity.celebrateTogether': 'Празнувайте заедно',
  'ourCommunity.celebrateTogetherDesc': 'Признавайте постижения, празнувайте етапи и вдъхновявайте един друг да достигнете нови височини.',
  'ourCommunity.supportNetwork': 'Мрежа за подкрепа',
  'ourCommunity.supportNetworkDesc': 'Намерете ментори, задавайте въпроси и получавайте насоки от опитни застъпници на околната среда.',
  'ourCommunity.schoolPartnerships': 'Училищни партньорства',
  'ourCommunity.schoolPartnershipsDesc': 'Свържете цялото си училище с други по света за съвместни екологични инициативи.',
  'ourCommunity.impact': 'Въздействие на общността',
  'ourCommunity.impactDesc': 'Нашата общност е засадила над 50 000 дървета, организирала 1000+ местни събития за почистване и достигнала до 500 000 ученици в 85 страни. Заедно доказваме, че колективните действия създават реална промяна.',
  'ourCommunity.countries': 'Страни',
  'ourCommunity.studentsCount': 'Ученици',
  'ourCommunity.treesPlanted': 'Засадени дървета',
  'ourCommunity.events': 'Събития',
  'ourCommunity.joinCommunity': 'Присъединете се към нашата общност',
  'ourCommunity.joinCommunityText': 'Станете част от глобално движение на ученици, предприемащи действия за нашата планета. Свързвайте се, споделяйте и правете промяна заедно.',
  'ourCommunity.exploreCommunity': 'Разгледайте общността',

  // Our Impact
  'ourImpact.title': 'Нашето въздействие',
  'ourImpact.subtitle': 'Реална промяна в околната среда чрез колективни действия',
  'ourImpact.measurable': 'Измерима промяна в околната среда',
  'ourImpact.measurableText': 'Всяко действие, предприето от нашата общност, създава реално, трайно въздействие. От намаляване на пластмасовите отпадъци до засаждане на гори, проследяваме и празнуваме всяка положителна промяна, която учениците ни правят.',
  'ourImpact.treesPlantedTitle': 'Засадени дървета',
  'ourImpact.treesPlantedDesc': 'Нашите проекти за повторно залесяване са засадили над 52 000 дървета, поглъщащи хиляди тонове CO2 годишно.',
  'ourImpact.plasticRemoved': 'Премахнати пластмасови предмети',
  'ourImpact.plasticRemovedDesc': 'Почистванията на плажове и общности са премахнали над 2 милиона пластмасови предмета от природни среди.',
  'ourImpact.behaviorChange': 'Промяна на поведението',
  'ourImpact.behaviorChangeDesc': '85% от учениците съобщават за трайни промени в екологичните си навици след завършване на нашите програми.',
  'ourImpact.schoolGardens': 'Училищни градини',
  'ourImpact.schoolGardensDesc': 'Инициативи, ръководени от ученици, са създали над 150 устойчиви училищни градини по целия свят.',
  'ourImpact.beyondNumbers': 'Отвъд числата',
  'ourImpact.beyondNumbersText': 'Нашето въздействие надхвърля статистиката. Учениците развиват лидерски умения, училищата въвеждат устойчиви политики, а общностите стават по-екологично съзнателни. Създаваме ефект на вълна, който докосва семейства, квартали и цели региони.',
  'ourImpact.studentStories': 'Истории на ученици',
  'ourImpact.studentStory1': 'Чрез P.I.G нашето училище засади 500 дървета и вдъхнови целия ни град да започне програма за рециклиране. Не просто учим - ние водим промяната.',
  'ourImpact.studentStory1Author': '— Мария, 16, Бразилия',
  'ourImpact.studentStory2': 'Организирах първото си почистване на плаж благодарение на P.I.G. Сега го правим месечно с 50+ доброволци!',
  'ourImpact.studentStory2Author': '— Давид, 14, Филипини',
  'ourImpact.bePartOfImpact': 'Бъдете част от въздействието',
  'ourImpact.bePartText': 'Присъединете се към хиляди ученици, създаващи реална промяна в околната среда. Вашите действия имат значение.',
  'ourImpact.startMakingImpact': 'Започнете да правите въздействие',

  // Our Values
  'ourValues.title': 'Нашите ценности',
  'ourValues.subtitle': 'Образование, действие и състрадание за всички живи същества',
  'ourValues.whatWeStandFor': 'Какво застъпваме',
  'ourValues.whatWeStandForText': 'Нашите ценности ръководят всяко решение, което вземаме, и оформят културата на нашата глобална общност. Те отразяват нашия ангажимент за създаване на по-добър свят за всички живи същества.',
  'ourValues.education': 'Образование',
  'ourValues.educationText': 'Знанието е сила. Вярваме в правенето на екологичното образование достъпно, ангажиращо и приложимо. Всеки ученик заслужава да разбере науката зад климатичните промени и решенията в техния обхват.',
  'ourValues.educationPoint1': 'Учебни материали, базирани на доказателства',
  'ourValues.educationPoint2': 'Достъпно за всички, независимо от произхода',
  'ourValues.educationPoint3': 'Практически знания, водещи до действие',
  'ourValues.action': 'Действие',
  'ourValues.actionText': 'Ученето трябва да води до действие. Овластяваме учениците да предприемат значими действия в своите общности, превръщайки осведомеността във въздействие. Всяко малко действие допринася за по-голяма промяна.',
  'ourValues.actionPoint1': 'Практически екологични проекти',
  'ourValues.actionPoint2': 'Инициативи, ръководени от общността',
  'ourValues.actionPoint3': 'Измеримо, реално въздействие',
  'ourValues.compassion': 'Състрадание',
  'ourValues.compassionText': 'Защитата на околната среда започва с грижата - за нашата планета, за всички видове и един за друг. Насърчаваме общност, изградена върху емпатия, уважение и доброта.',
  'ourValues.compassionPoint1': 'Уважение към всички живи същества',
  'ourValues.compassionPoint2': 'Приобщаваща и подкрепяща общност',
  'ourValues.compassionPoint3': 'Разбиране на различни гледни точки',
  'ourValues.collaboration': 'Сътрудничество',
  'ourValues.collaborationText': 'Никой не може да реши климатичната криза сам. Вярваме в силата на колективните действия, обединявайки ученици, училища и общности по целия свят.',
  'ourValues.collaborationPoint1': 'Глобална мрежа от създатели на промяна',
  'ourValues.collaborationPoint2': 'Споделени знания и ресурси',
  'ourValues.collaborationPoint3': 'По-силни заедно, отколкото поотделно',
  'ourValues.livingValues': 'Живеем с нашите ценности', 
  'ourValues.livingValuesText': 'Това не са просто думи на страница - те са принципи, които практикуваме всеки ден. От начина, по който проектираме учебната си програма, до начина, по който подкрепяме общността си, нашите ценности ни водят напред.',
  'ourValues.livingValuesText2': 'Когато се присъедините към PIG, ставате част от движение, което приоритизира образованието, празнува действията, практикува състрадание и процъфтява чрез сътрудничество.', 
  'ourValues.joinMission': 'Присъединете се към нашата мисия', 
  'ourValues.joinMissionText': 'Готови ли сте да бъдете част от общност, която живее тези ценности всеки ден? Започнете пътуването си с PIG.', 
  'ourValues.learnMore': 'Научете повече за нас',

  // About Page Cards
  'about.ourGoal': 'Нашата цел',
  'about.ourGoalDesc': 'Правим екологичното образование достъпно за всеки ученик по света',
  'about.ourCommunity': 'Нашата общност',
  'about.ourCommunityDesc': 'Свързваме училища и ученици по целия свят',
  'about.ourImpact': 'Нашето въздействие',
  'about.ourImpactDesc': 'Реална промяна в околната среда чрез колективни действия',
  'about.ourValues': 'Нашите ценности',
  'about.ourValuesDesc': 'Образование, действие и състрадание за всички живи същества',

  // Learn Page Topics and Content
  'learn.searchPlaceholder': 'Търсене на теми...',
  'learn.topic.wildlife.title': 'Защита на дивата природа',
  'learn.topic.wildlife.subtitle1': 'Защо всяко животно е важно',
  'learn.topic.wildlife.text1': 'Всяко същество, от най-малкото насекомо до най-голямия кит, играе решаваща роля в нашата екосистема. Когато един вид изчезне, това засяга цялата хранителна верига и може да има опустошителни последици за нашата планета.',
  'learn.topic.wildlife.subtitle2': 'Как можете да помогнете',
  'learn.topic.wildlife.text2': 'Създайте пространства, приятелски за дивата природа във вашата градина, избягвайте използването на вредни пестициди, подкрепяйте природозащитни организации и никога не замърсявайте в естествени местообитания. Малките действия водят до големи промени!',
  'learn.topic.pollution.title': 'Борба със замърсяването',
  'learn.topic.pollution.subtitle1': 'Въздействието на замърсяването',
  'learn.topic.pollution.text1': 'Замърсяването вреди на нашия въздух, вода и почва. То засяга не само дивата природа, но и нашето здраве. Пластмасовите отпадъци, химическият отток и замърсяването на въздуха са едни от най-големите заплахи за околната среда.',
  'learn.topic.pollution.subtitle2': 'Предприемане на действия',
  'learn.topic.pollution.text2': 'Намалете използването на пластмаси за еднократна употреба, изхвърляйте отпадъците правилно, използвайте екологични продукти и насърчавайте другите да правят същото. Всяко парче боклук, изхвърлено правилно, е една заплаха по-малко за нашата планета.',
  'learn.topic.recycling.title': 'Рециклиране и повторна употреба',
  'learn.topic.recycling.subtitle1': 'Силата на рециклирането',
  'learn.topic.recycling.text1': 'Рециклирането спестява природни ресурси, намалява отпадъците в депата и пести енергия. Когато рециклираме хартия, спасяваме дървета. Когато рециклираме пластмаса, намаляваме замърсяването на океаните.',
  'learn.topic.recycling.subtitle2': 'Как да рециклираме правилно',
  'learn.topic.recycling.text2': 'Научете какво може да се рециклира във вашия район, почиствайте предметите преди рециклиране, намалявайте отпадъците чрез повторна употреба и компостирайте органичните отпадъци. Направете рециклирането ежедневен навик!',
  'learn.topic.forests.title': 'Опазване на горите',
  'learn.topic.forests.subtitle1': 'Защо горите са важни',
  'learn.topic.forests.text1': 'Горите са белите дробове на нашата планета. Те произвеждат кислород, съхраняват въглероден диоксид, осигуряват дом на безброй видове и помагат за регулирането на климата. Защитата на горите е от решаващо значение за нашето оцеляване.',
  'learn.topic.forests.subtitle2': 'Какво можете да направите',
  'learn.topic.forests.text2': 'Садете дървета, използвайте по-малко хартия, избирайте устойчиви дървесни продукти и подкрепяйте усилията за повторно залесяване. Дори засаждането на едно дърво прави разлика!',
  'learn.topic.water.title': 'Опазване на водата',
  'learn.topic.water.subtitle1': 'Водата е ценна',
  'learn.topic.water.text1': 'Чистата вода е от съществено значение за целия живот на Земята. Въпреки това замърсяването и отпадъците заплашват водните ни източници. Само 3% от водата на Земята е прясна вода и голяма част от нея е замразена в ледници.',
  'learn.topic.water.subtitle2': 'Пестете вода ежедневно',
  'learn.topic.water.text2': 'Изключвайте крановете, когато не ги използвате, поправяйте течовете, взимайте по-кратки душове и никога не замърсявайте водните източници. Всяка спестена капка помага да осигурим вода за бъдещите поколения.',
  'learn.topic.community.title': 'Действия на общността',
  'learn.topic.community.subtitle1': 'По-силни заедно',
  'learn.topic.community.text1': 'Индивидуалните действия са важни, но когато общностите работят заедно, можем да постигнем невероятни неща. Организирайте събития за почистване, стартирайте програми за рециклиране и вдъхновете другите да се присъединят към каузата.',
  'learn.topic.community.subtitle2': 'Как да се включите',
  'learn.topic.community.text2': 'Говорете с учителите си за стартиране на екологични проекти, присъединете се или създайте еко-клубове, участвайте в общностни почиствания и споделяйте наученото с приятели и семейство.',
  'learn.topic.climate.title': 'Климатични промени',
  'learn.topic.biodiversity.title': 'Биоразнообразие',
  'learn.topic.mountains.title': 'Планински екосистеми',
  'learn.topic.oceans.title': 'Океански живот',
  'learn.topic.birds.title': 'Защита на птиците',
  'learn.topic.gardens.title': 'Устойчиви градини',
  'learn.topic.global.title': 'Глобални инициативи',
  'learn.topic.energy.title': 'Зелена енергия',
  'learn.topic.education.title': 'Еко образование',
  'learn.topic.agriculture.title': 'Устойчиво земеделие',
  'learn.topic.comingSoon': 'Очаквайте скоро',
  'learn.topic.comingSoonText': 'Съдържанието ще бъде добавено тук.',

  // FAQ Questions and Answers
  'faq.q1': 'Какво е P.I.G?',
  'faq.a1': 'P.I.G е образователна платформа, която учи учениците за опазването на околната среда чрез интерактивно обучение, състезания и ангажиране на общността.',
  'faq.q2': 'Кой може да се присъедини към P.I.G?',
  'faq.a2': 'P.I.G е отворен за ученици от всички възрасти, учители, училищни администратори и родители. Всеки тип потребител има различни нива на достъп и функции.',
  'faq.q3': 'Как работят състезанията?',
  'faq.a3': 'Състезанията се провеждат седмично, месечно и годишно на ниво град, училище и индивидуален ученик. Участниците печелят точки за завършване на екологични предизвикателства и действия.',
  'faq.q4': 'Безплатен ли е P.I.G?',
  'faq.a4': 'Да! P.I.G е напълно безплатен за всички ученици и преподаватели. Нашата мисия е да направим екологичното образование достъпно за всички.',
  'faq.q5': 'Как може училището ми да се присъедини?',
  'faq.a5': 'Училищните администратори могат да регистрират училището си чрез нашата платформа. След регистрация учителите могат да създават групи и да канят ученици да се присъединят.',
  'faq.q6': 'Какви дейности можем да публикуваме?',
  'faq.a6': 'Училищата могат да споделят снимки и актуализации за кампании за рециклиране, събития за засаждане на дървета, дейности по почистване и всякакви екологични инициативи, предприети от учениците.',
  'faq.q7': 'Как се определят победителите в състезанията?',
  'faq.a7': 'Победителите се определят от точки, спечелени чрез проверени екологични действия. Училищата и градовете с най-активни участници получават признание.',
  'faq.q8': 'Могат ли родителите да следят напредъка на детето си?',
  'faq.a8': 'Да! Родителите с акаунти могат да следват групата на училището на детето си и да виждат екологичните дейности, в които то участва.',

  // Privacy Page Content
  'privacy.intro': 'Въведение',
  'privacy.introText': 'В P.I.G се отнасяме сериозно към поверителността ви. Тази Политика за поверителност обяснява как събираме, използваме, разкриваме и защитаваме вашата информация, когато използвате нашата платформа.',
  'privacy.collect': 'Информация, която събираме',
  'privacy.collectText': 'Събираме информация, която ни предоставяте директно, включително:',
  'privacy.collectItem1': 'Име, имейл адрес и информация за училището',
  'privacy.collectItem2': 'Данни за акаунта',
  'privacy.collectItem3': 'Профилна информация и снимки',
  'privacy.collectItem4': 'Публикации, коментари и друго съдържание, което споделяте',
  'privacy.use': 'Как използваме вашата информация',
  'privacy.useText': 'Използваме събраната информация за:',
  'privacy.useItem1': 'Предоставяне и поддържане на нашите услуги',
  'privacy.useItem2': 'Улесняване на състезания и функции на общността',
  'privacy.useItem3': 'Изпращане на важни актуализации и известия',
  'privacy.useItem4': 'Подобряване на нашата платформа и потребителско изживяване',
  'privacy.sharing': 'Споделяне на информация',
  'privacy.sharingText': 'Не продаваме вашата лична информация. Може да споделяме информация с училища и родители като част от нашата образователна мисия, но само с подходящо съгласие.',
  'privacy.children': 'Поверителност на децата',
  'privacy.childrenText': 'Ангажирани сме да защитаваме поверителността на децата. Родителите и настойниците имат контрол над акаунтите на децата си и могат да преглеждат или изтриват информация по всяко време.',
  'privacy.contact': 'Свържете се с нас',
  'privacy.contactText': 'Ако имате въпроси относно тази Политика за поверителност, моля свържете се с нас.',

  // Terms Page Content
  'terms.acceptance': 'Приемане на условията',
  'terms.acceptanceText': 'С достъпа и използването на P.I.G, вие приемате и се съгласявате да бъдете обвързани от условията и разпоредбите на това споразумение.',
  'terms.use': 'Използване на платформата',
  'terms.useText': 'P.I.G е предназначен за образователни цели. Потребителите се съгласяват да:',
  'terms.useItem1': 'Предоставят точна информация при регистрация',
  'terms.useItem2': 'Поддържат сигурността на своя акаунт',
  'terms.useItem3': 'Използват платформата отговорно и с уважение',
  'terms.useItem4': 'Не публикуват вредно, обидно или неподходящо съдържание',
  'terms.accounts': 'Училищни и ученически акаунти',
  'terms.accountsText': 'Училищните администратори са отговорни за управлението на присъствието на училището им в платформата. Учениците под 13 години трябва да имат родителско съгласие, за да използват платформата.',
  'terms.competition': 'Правила за състезания',
  'terms.competitionText': 'Участниците в състезания трябва да спазват всички правила и насоки. P.I.G си запазва правото да дисквалифицира участници, които нарушават правилата на състезанието или участват в измамни дейности.',
  'terms.content': 'Собственост на съдържанието',
  'terms.contentText': 'Потребителите запазват собствеността върху съдържанието, което публикуват, но предоставят на P.I.G лиценз да използва, показва и разпространява това съдържание в рамките на платформата.',
  'terms.prohibited': 'Забранени дейности',
  'terms.prohibitedText': 'Потребителите не могат да:',
  'terms.prohibitedItem1': 'Нарушават закони или разпоредби',
  'terms.prohibitedItem2': 'Тормозят или вредят на други потребители',
  'terms.prohibitedItem3': 'Опитват се да достъпят неоторизирани области на платформата',
  'terms.prohibitedItem4': 'Качват зловреден код или спам',
  'terms.termination': 'Прекратяване',
  'terms.terminationText': 'Запазваме си правото да прекратяваме или спираме акаунти, които нарушават тези условия или участват в неподходящо поведение.',
  'terms.changes': 'Промени в условията',
  'terms.changesText': 'Може да актуализираме тези условия от време на време. Продължаването на използването на платформата след промени представлява приемане на новите условия.',
  'terms.contact': 'Контакт',
  'terms.contactText': 'Въпроси относно тези Условия за ползване могат да бъдат насочени към нас.',

  // Profile
  'profile.complete': 'Завършено',
  'profile.logout': 'Изход',

  // Community Page
  'community.title': 'Общност',
  'community.public': 'Публична емисия',
  'community.feeds': 'Емисии',
  'community.myGroups': 'Моите групи',
  'community.moderation': 'Модерация',
  'community.globalCommunity': 'Глобална общност',
  'community.mySchool': 'Моето училище',
  'community.myClass': 'Моят клас',
  'community.schoolGroup': 'Училищна група',
  'community.classGroup': 'Класна група',
  'community.publicSubtitle': 'Екологични инициативи от училища по целия свят',
  'community.schoolSubtitle': 'Новини и събития от вашето училище',
  'community.classSubtitle': 'Класни дискусии и проекти',
  'community.groupUpdates': 'Групови актуализации',
  'community.createPost': 'Създай публикация',
  'community.createNewPost': 'Създай нова публикация',
  'community.sharePlaceholder': 'Споделете нещо с',
  'community.everyone': 'всички',
  'community.yourGroup': 'вашата група',
  'community.photo': 'Снимка',
  'community.post': 'Публикувай',
  'community.noPostsYet': 'Все още няма публикации',
  'community.beTheFirst': 'Бъдете първият, който споделя нещо с',
  'community.communityWord': 'общността!',
  'community.save': 'Запази',
  'community.writeComment': 'Напишете коментар...',
  'community.commentAdded': 'Коментарът е добавен!',
  'community.commentAddedDesc': 'Вашият коментар беше публикуван успешно.',
  'community.postCreated': 'Публикацията е създадена!',
  'community.postCreatedDesc': 'Вашата публикация беше споделена.',
  'community.postDeleted': 'Публикацията е изтрита',
  'community.postDeletedDesc': 'Вашата публикация беше премахната.',
  'community.postUpdated': 'Публикацията е актуализирана',
  'community.postUpdatedDesc': 'Вашата публикация беше актуализирана успешно.',
  'community.commentDeleted': 'Коментарът е изтрит',
  'community.commentDeletedDesc': 'Вашият коментар беше премахнат.',
  'community.commentUpdated': 'Коментарът е актуализиран',
  'community.commentUpdatedDesc': 'Вашият коментар беше актуализиран успешно.',

  // Admin Panel
  'admin.title': 'Админ',
  'admin.managementConsole': 'Управленска конзола',
  'admin.overview': 'Преглед',
  'admin.groups': 'Групи',
  'admin.users': 'Потребители',
  'admin.reports': 'Доклади',
  'admin.settings': 'Настройки',
  'admin.exitMode': 'Изход от режима',
  'admin.adminConsole': 'Админ конзола',
  'admin.createGroup': 'Създай група',
  'admin.systemOverview': 'Преглед на системата',
  'admin.groupManagement': 'Управление на групи',
  'admin.userManagement': 'Управление на потребители',
  'admin.globalSettings': 'Глобални настройки',
  'admin.contentModeration': 'Модерация на съдържание',
  'admin.manageSubtitle': 'Управлявайте, наблюдавайте и поддържайте стандартите на общността.',
  'admin.latestUpdates': 'Последни актуализации от вашата общност.',
  'admin.totalUsers': 'Общо потребители',
  'admin.fromLastWeek': '+2% от миналата седмица',
  'admin.activeGroups': 'Активни групи',
  'admin.pendingReports': 'Чакащи доклади',
  'admin.actionRequired': 'Необходимо е действие',
  'admin.allClear': 'Всичко е наред',
  'admin.systemStatus': 'Състояние на системата',
  'admin.serversOperational': 'Сървърите работят',
  'admin.globalAnnouncement': 'Глобално съобщение',
  'admin.announcementDesc': 'Изпратете съобщение до всички активни чат стаи.',
  'admin.announcementPlaceholder': "Напишете съобщението си тук (напр. 'Поддръжка на сървъра след 10 минути')...",
  'admin.broadcast': 'Излъчване',
  'admin.announcementSent': 'Съобщението е изпратено',
  'admin.announcementSentDesc': 'Всички потребители са уведомени.',
  'admin.recentActivityLog': 'Последна активност',
  'admin.activityLogDesc': 'История на административните действия.',
  'admin.searchUsers': 'Търсене на потребители по име или имейл...',
  'admin.exportCsv': 'Експорт CSV',
  'admin.user': 'Потребител',
  'admin.role': 'Роля',
  'admin.status': 'Статус',
  'admin.actions': 'Действия',
  'admin.manage': 'Управление',
  'admin.viewProfile': 'Виж профил',
  'admin.resetPassword': 'Нулиране на парола',
  'admin.deleteAccount': 'Изтрий акаунт',
  'admin.chatGroups': 'Чат групи',
  'admin.members': 'членове',
  'admin.noDescription': 'Без описание',
  'admin.freeze': 'Замрази',
  'admin.unfreeze': 'Размрази',
  'admin.groupStatusUpdated': 'Статусът на групата е актуализиран',
  'admin.groupDeleted': 'Групата е изтрита',
  'admin.allCaughtUp': 'Всичко е наред!',
  'admin.noPendingReports': 'Няма чакащи доклади за преглед.',
  'admin.reported': 'Докладвано',
  'admin.reportedBy': 'Докладвано от',
  'admin.postContent': 'Съдържание на публикацията:',
  'admin.contentUnavailable': 'Съдържанието не е налично (Изтрито или Грешка)',
  'admin.dismissReport': 'Отхвърли доклада',
  'admin.deletePost': 'Изтрий публикацията',
  'admin.contentRemoved': 'Съдържанието е премахнато',
  'admin.contentRemovedDesc': 'Публикацията е изтрита завинаги.',
  'admin.reportDismissed': 'Докладът е отхвърлен',
  'admin.safetyFilters': 'Безопасност и филтри',
  'admin.safetyFiltersDesc': 'Глобални настройки за всички чат стаи.',
  'admin.profanityFilter': 'Филтър за нецензурни думи',
  'admin.profanityFilterDesc': 'Автоматично скриване на обидни думи.',
  'admin.imageUploads': 'Качване на изображения',
  'admin.imageUploadsDesc': 'Позволете на потребителите да изпращат изображения в чатове.',
  'admin.linkPreview': 'Преглед на линкове',
  'admin.linkPreviewDesc': 'Генериране на прегледи за споделени URL адреси.',
  'admin.dangerZone': 'Опасна зона',
  'admin.maintenanceMode': 'Включи режим на поддръжка',
  'admin.maintenanceModeDesc': 'Това ще заключи всички чат стаи за всички освен администраторите.',
  'admin.userBanned': 'Потребителят е блокиран',
  'admin.userUnbanned': 'Потребителят е разблокиран',

  // Create Group Dialog
  'group.createTitle': 'Създай нова група',
  'group.createDesc': 'Създайте пространство за ученици и учители за сътрудничество.',
  'group.orSelectPreset': 'Или изберете готова икона:',
  'group.iconSelected': 'Иконата е избрана',
  'group.browseIcons': 'Разгледай икони',
  'group.groupName': 'Име на групата',
  'group.groupNamePlaceholder': 'напр. Научен панаир 2024',
  'group.description': 'Описание',
  'group.descriptionPlaceholder': 'За какво е тази група?',
  'group.organization': 'Организация',
  'group.selectOrganization': 'Изберете организация',
  'group.none': 'Няма',
  'group.orgPassword': 'Парола на организацията',
  'group.orgPasswordNotRequired': 'Не е необходима',
  'group.orgPasswordRequired': 'Необходима за свързване с тази организация',
  'group.privacyType': 'Тип поверителност',
  'group.public': 'Публична',
  'group.private': 'Частна',
  'group.accessCode': 'Код за достъп',
  'group.accessCodePlaceholder': 'Задайте парола за присъединяване...',
  'group.cancel': 'Откажи',
  'group.create': 'Създай група',
  'group.created': 'Групата е създадена',
  'group.createdDesc': 'вече е активна.',

};
